### ISSUE TITLE
Fix 6 failing cucumber steps

### ISSUE THREAD

**Issue by mattlindsey** [strawberrycanyon/redeemify#2]
Run 'cucumber features' to see that 6 cucumber steps are failing:
  Failing Scenarios:
1  cucumber features/provider_withdraw.feature:14 # Scenario:
2 cucumber features/user_login.feature:19 # Scenario: unsuccessful login after entering invalid  credentials, redirected back to home page
3  cucumber features/vendor_provider_download.feature:19 # Scenario:
4  cucumber features/vendor_remove_history.feature:12 # Scenario:
5  cucumber features/vendor_remove_history.feature:25 # Scenario:
6  cucumber features/vendor_withdraw.feature:19 # Scenario:

**Comment by armandofox** [comment]
yep, those are the ones that were failing in the rails3 version when i first released it...

**Comment by mattlindsey** [comment]
Fixed by https://github.com/strawberrycanyon/redeemify/pull/3
This issue can be closed.
