### ISSUE TITLE
Fix low Code Climate score

### ISSUE THREAD

**Issue by mattlindsey** [strawberrycanyon/redeemify#21]
one easy thing to fix is there is a very low codeclimate score because apparently some minified .js files are included in the mix, and apparently some asset-pipeline-generated .js files are under versin control (they shouldn't be).  fixing these to get true sense of code quality would be great...

**Comment by mattlindsey** [comment]
hi @arun1595.  are you working on this?  We can do it together if you want, or I can do it.

**Comment by arun1595** [comment]
@mattlindsey I am working on it. Will submit a PR soon!
