### ISSUE TITLE
Vendor Code displaying as $0 value (good issue for new project member)

### ISSUE THREAD

**Issue by mattlindsey** [strawberrycanyon/redeemify#24]
After hitting 'developer' link to log in as a developer, then entering a 'Redeemify' code like 'yyyyy', the 'Vendor' code is displayed with a $0 value when it should say $10.

Note that this was working before the PROVIDER_CODE table was renamed to REDEEMIFY_CODE.

![screen shot 2016-10-30 at 6 41 52 pm](https://cloud.githubusercontent.com/assets/5638339/19840636/d998e280-9ed0-11e6-8cda-8a7848c7fbb0.png)

**Comment by mattlindsey** [comment]
Hold off on this one since it depends on the table rename PR #20.

**Comment by mattlindsey** [comment]
Anyone can take this now.  Just be sure to pull latest code and reset db first.

**Comment by sic-f** [comment]
will work on this one.
