### ISSUE TITLE
Provider Home Page formatting is bad (good for new project member)

### ISSUE THREAD

**Issue by mattlindsey** [strawberrycanyon/redeemify#27]
Fix formatting for Provider Home Page.  
Note that to get to the page you'll have to add yourself as a Provider as described in 'Developer Tips' in the CONTRIBUTING.md file.

![image](https://cloud.githubusercontent.com/assets/5638339/19853884/5ca25a96-9f42-11e6-954a-68fa99a5a023.png)

**Comment by arun1595** [comment]
Let me work on this.
