### ISSUE TITLE
Deprecation messages when running rspec or cucumber (good for new project member)

### ISSUE THREAD

**Issue by mattlindsey** [strawberrycanyon/redeemify#36]
Resolve following messages:

rspec spec
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/less-rails-2.7.1/lib/less/rails/railtie.rb:15)
DEPRECATION WARNING: You are using the a deprecated processor interface Less::Rails::ImportProcessor.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/less-rails-2.7.1/lib/less/rails/railtie.rb:20)
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in <class:Railtie> at /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/sass-rails-5.0.5/lib/sass/rails/railtie.rb:57)
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in <class:Railtie> at /Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/sass-rails-5.0.5/lib/sass/rails/railtie.rb:58)

**Comment by sic-f** [comment]
This gets fixed when removing less-rails in the Gemfile. Do we need it? Since I'm using Sass anyway for CSS and is also the default with Rails.

Less has problems with sprockets 3.7 which is our version.
https://github.com/metaskills/less-rails/issues/122

I'll include this fix in the Deprecations in rspec issue #37 pull request
