### ISSUE TITLE
EPIC: Add authentication the api 'get' endpoint

### ISSUE THREAD

**Issue by mattlindsey** [strawberrycanyon/redeemify#44]
The flow for authenticating the user through an API is very simple:

The client request for sessions resource with the corresponding credentials, usually email and password.
The server returns the user resource along with its corresponding authentication token
Every page that requires authentication, the client has to send that authentication token

It does require adding an 'authentication_key' column to the Users table.  

Comments?  Should we instead have one 'api_key'?

**Comment by tansaku** [comment]
Superficially it feels like each separate user should be authenticated ...

**Comment by mattlindsey** [comment]
Note that this issue is an EPIC whose individual stories are in the 'Projects' tab.

**Comment by mattlindsey** [comment]
Closing because this issue is now in PT.
