### ISSUE TITLE
Failing cucumber scenarios

### ISSUE THREAD

**Issue by mattlindsey** [strawberrycanyon/redeemify#47]
Hi @sic-f.  Are you working on this? :)

Failing Scenarios:
cucumber features/enter_code.feature:12 # Scenario: login successful after entering correct serial code
cucumber features/register_new_account.feature:8 # Scenario: login successful after entering correct serial code
cucumber features/user_delete_account.feature:12 # Scenario: vendor change offer profile
cucumber features/user_login.feature:12 # Scenario: successful login after entering valid credentials
cucumber features/user_login.feature:19 # Scenario: unsuccessful login after entering invalid credentials, redirected back to home page
cucumber features/user_new_offer.feature:19 # Scenario: vendor change offer profile
cucumber features/vendor_login_as_user.feature:15 # Scenario:
cucumber features/view_offer.feature:21 # Scenario:

**Comment by sic-f** [comment]
Hi @mattlindsey not yet. I've been planning to tell you about this since I think those test broke when I did the CSS. Let me look at it. Thanks!

**Comment by mattlindsey** [comment]
To solve this we think we have to make a version of the page with enabled JS with corresponding tests.

**Comment by sic-f** [comment]
I agree, and to work with Alex as well on this.

**Comment by sic-f** [comment]
We can close this now as Alex has fixed the failing Cucumber tests.
