### ISSUE TITLE
Fix some sloppy code and formatting

### ISSUE THREAD

**Issue by mattlindsey** [strawberrycanyon/redeemify#48]
This is just a placeholder for now.  I will try to identify where the code can be refactored.

**Comment by mattlindsey** [comment]
I think in vendor_controller.rb, the line "@vendor = Vendor.find(session[:vendor_id])" should be put into a private method.
Probably some code should be moved to the model to make this a 'skinny controller.'

**Comment by mattlindsey** [comment]
Also sessions_controller.rb should be made 'skinny.'

**Comment by sic-f** [comment]
I'll work on this issue @mattlindsey.
