### ISSUE TITLE
Duplication of code in the controllers

### ISSUE THREAD

**Issue by alexander-kh** [strawberrycanyon/redeemify#74]
The goal is to eliminate Code Climate issues associated with the duplication of code in the controllers.

**Comment by tansaku** [comment]
my concern is with method length - I like Sandi Metz's heuristic of max 5 lines per method

**Comment by alexander-kh** [comment]
I like this standard too. If follow the SOFA principles, quantitatively it can be expressed in these limits, I guess.
I have to read her books.

**Comment by alexander-kh** [comment]
The initial goal was achieved and all the duplication related issues were solved (pull request #75). I'm closing this issue and open the new, more specific one, with the @tansaku remark related to methods length in the controllers.
