### ISSUE TITLE
Tracking of used vendor codes

### ISSUE THREAD

**Issue by alexander-kh** [strawberrycanyon/redeemify#79]
A [good question](https://github.com/strawberrycanyon/redeemify/pull/77#discussion_r105552522) has been raised by @uzzsen during pull request reviewing. It interrelates with the question related to the purpose of `cash_value` attribute in Vendor model.
Armando noted:
> I think the farthest we should go is to make it simple to copy a redemption code to clipboard.

It means that there are no particular reasons to define values for each offer if only it is not the foundation for future extensions of the app.

**Comment by alexander-kh** [comment]
Let's consider several scenarios.
1. All offers are free and always will be free.
`cash_value` will only illustrate how much will save holder of the redemption code.
In this case, all vendor codes could be considered used when the user logs in to the app using master token.
Also, we have to add validations for this attribute in the Vendor model and make this field required on the vendor profile page.
The another pathway is to eliminate it as a redundant entity.
2. Some business perspectives.
We keep it, and in this case may be useful to track used vendor codes separately from all the displayed ones.

**Comment by alexander-kh** [comment]
I've revised changes in vendor_code.rb and have kept original code and RSpec test in accordance with scenario 1.
Thanks, @uzzsen.

**Comment by Uzzsen** [comment]
@alexander-kh 
I am glad you'I've revised the vendor profile page enabling vendors to update the `cash_value` attribute. It used to be plain text area. 

I am not sure of the constraint to require vendors to input some value. However whatever value is input it has to be a number as these are summed up across all vendors for every Redemify user.

**Comment by alexander-kh** [comment]
I also think `string` is not the best type for the numeric value. Will be interesting to know original intentions, why it was chosen. Perhaps that `Free` looks better than `0`.
I propose to get an answer from the stakeholders concerning its purpose and then make a decision.

**Comment by Uzzsen** [comment]
@alexander-kh:
What I mean by zero - `0` - is the system default value to get stored in the db, with Redemify user seeing a blank for `cash_value` (if unedited by vendor). As a user, you won't be interested to acquire some benefit of _no_ (0) value to you and, therefore, will not use the vendor code. The term _Free_ usually aplies to price (what you pay) and not the value you get in exchange for money . 

The vendor, however in my view, should explicitly see 0 `Cash value` on the edit profile form implying it should better be greater and edited or the Redemify users won't visit the vendor site to collect the benefit.

**Comment by mattlindsey** [comment]
I agree with @alexander-kh in scenario 1 above, so it seems to me that tasks are:
1) all vendor codes should be considered used when the user logs in to the app using master token
2) add validations for this attribute in the Vendor model and make this field required on the vendor profile page, with initial value of 0
