### ISSUE TITLE
Schema update

### ISSUE THREAD

**Issue by alexander-kh** [strawberrycanyon/redeemify#80]
Friends, what do you think about schema updating?
The objective is to add the necessary attribute, remove unused one and change style of codes-related attributes. The code is structured pretty well and covered by tests, and it is sensible to make changes before adding new features and deploying.
Will be good to reach an agreement regarding `cash_value` attribute, its type, and purpose in general.
Any suggestions are very welcome.
I propose to do the following.

Providers
```ruby
rails generate migration ChangeProviders
```
```ruby
change_table :providers do |t|
  t.string :uid
  t.rename :uploadedCodes, :uploaded_codes
  t.rename :usedCodes, :used_codes
  t.rename :unclaimCodes, :unclaimed_codes
  t.rename :removedCodes, :removed_codes
end
```
Vendors
```ruby
rails generate migration ChangeVendors
```
```ruby
change_table :vendors do |t|
  t.rename :helpLink, :help_link
  t.rename :cashValue, :cash_value
  t.rename :uploadedCodes, :uploaded_codes
  t.rename :usedCodes, :used_codes
  t.rename :unclaimCodes, :unclaimed_codes
  t.rename :removedCodes, :removed_codes
end
```

```ruby
rails generate migration ChangeVendorsCashValue
```
```
class ChangeVendorsCashValue < ActiveRecord::Migration
  def up
    change_table :vendors do |t|
      t.change :cash_value,
        'DECIMAL(5,2) USING CAST(cash_value AS DECIMAL(5,2))', default: 0
    end
  end
    
  def down
    change_table :vendors do |t|
      t.change :cash_value, :string
    end
  end
end
```
VendorCodes
```ruby
rails generate migration ChangeVendorCodes
```
```ruby
change_table :vendor_codes do |t|
  t.remove :vendor
end
```

**Comment by mattlindsey** [comment]
Looks good to me!

**Comment by alexander-kh** [comment]
Added migration to change `cash_value` type to decimal, precision: 5, scale: 2.
Check one more time all the attributes, please.
Any additional suggestions regarding names can be considered.
Do we keep the name of the model RedeemifyCode instead of RedemptionCode, for example?

**Comment by mattlindsey** [comment]
I agree to change cash_value to decimal(5,2).
I vote to keep name of RedeemifyCode, since it's fairly clear already.

**Comment by alexander-kh** [comment]
Thanks! Agree.
